using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices;

namespace EntityFrameworkCourse.Models {
	public class Task {

		//[Key]
		public Guid TaskId { get; set; }

		//[ForeignKey("CategoriaId")]
		public Guid CategoryId { get; set; }

		//[Required, MaxLength(200)]
		public string? Title { get; set; }

		//[MaxLength(500)]
		public string? Description { get; set; }

		//[Required]
		public Priority TaskPriority { get; set; }
		//[Required]
		public DateTime TaskCreated { get; set; }

		public virtual Category Category { get; set; }

		//[NotMapped]
		public string Resumen {  get; set; }
	}

	//Entity framework reprents these enums with integers in the database autogenerated.
	public enum Priority {
		Low,
		High,
		Avg
	}
}
